import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

//keeping incase, but not necessary for this project since we're using DM Mono as the main font
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmMono = localFont({
  src: [
    {
      path: "./fonts/DM_MONO/DMMono-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/DM_MONO/DMMono-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/DM_MONO/DMMono-Medium.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-dm-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${dmMono.variable}
          font-dm-mono antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
